return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "basedpyright",
      "bash-language-server",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "gofumpt",
      "goimports",
      "gopls",
      "hadolint",
      "jq",
      "json-lsp",
      "jsonlint",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "pyright",
      "ruff",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "vtsls",
      "vue-language-server",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
    },
  },
}
