return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "jq",
      "json-lsp",
      "jsonlint",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "vtsls",
      "vue-language-server",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
    },
  },
}
